name: Unit Test / Lint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run install
        run: yarn
      - name: Run test
        run: yarn cypress run-ct --browser chrome --headless
